### ISSUE TITLE
Init não cria user

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#109]

**Comment by gustavorsilva** [comment]
erro para criar usuario
```shell
W20180220-08:57:52.977(-3)? (STDERR) 
W20180220-08:57:52.978(-3)? (STDERR) /home/gustavo/.meteor/packages/meteor-tool/.1.6.0.1j45arq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180220-08:57:52.979(-3)? (STDERR) 						throw(ex);
W20180220-08:57:52.979(-3)? (STDERR) 						^
W20180220-08:57:53.231(-3)? (STDERR) Error: "emails" is required [validation-error]
W20180220-08:57:53.233(-3)? (STDERR)     at new ValidationError (packages/mdg:validation-error/validation-error.js:14:12)
W20180220-08:57:53.233(-3)? (STDERR)     at throwError (packages/jagi:astronomy/lib/modules/validators/validator.js:68:15)
W20180220-08:57:53.233(-3)? (STDERR)     at Validator.validate (packages/jagi:astronomy/lib/modules/validators/validator.js:95:9)
W20180220-08:57:53.234(-3)? (STDERR)     at Object.Validators.(anonymous function) [as required] (packages/jagi:astronomy/lib/modules/validators/validator.js:107:17)
W20180220-08:57:53.234(-3)? (STDERR)     at ListField.validate (packages/jagi:astronomy/lib/modules/fields/Field.js:35:18)
W20180220-08:57:53.234(-3)? (STDERR)     at ListField.validate (packages/jagi:astronomy/lib/modules/fields/ListField.js:19:11)
W20180220-08:57:53.234(-3)? (STDERR)     at catchValidationError (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:125:13)
W20180220-08:57:53.234(-3)? (STDERR)     at catchValidationError (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:49:7)
W20180220-08:57:53.235(-3)? (STDERR)     at name (packages/jagi:astronomy/lib/modules/validators/utils/document_validate.js:123:5)
W20180220-08:57:53.235(-3)? (STDERR)     at arrayEach (/home/gustavo/.meteor/packages/jagi_astronomy/.2.5.2.ytrfqa.jtln++os+web.browser+web.cordova/npm/node_modules/lodash/_arrayEach.js:15:9)
=> Exited with code: 1
W20180220-08:57:56.568(-3)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20180220-08:57:56.569(-3)? (STDERR) While this implementation will work correctly, it is known to be
W20180220-08:57:56.569(-3)? (STDERR) approximately three times slower than the native implementation.
W20180220-08:57:56.569(-3)? (STDERR) In order to use the native implementation instead, run
W20180220-08:57:56.570(-3)? (STDERR) 
W20180220-08:57:56.570(-3)? (STDERR)   meteor npm install --save bcrypt
W20180220-08:57:56.570(-3)? (STDERR) 
W20180220-08:57:56.570(-3)? (STDERR) in the root directory of your `application.
```

**Comment by andredornas** [comment]
Acho que sei o que é.

Na hook de [login](https://github.com/lern-edu/lern/blob/develop/server/hooks/login.js), o campo `user.email` é setado só nos "ifs" de login social. 

```
if (_.get(user, 'services.facebook')) {
        const face = _.get(user, 'services.facebook');
        user.profile = {
          firstName: _.get(face, 'first_name'),
          lastName: _.get(face, 'last_name'),
          name: _.get(face, 'name'),
          profilePic: `http://graph.facebook.com/${_.get(face, 'id')}/picture?type=square`,
          gender: _.get(face, 'gender'),
        };
        if (_.get(face, 'email'))
          user.emails = [{ address: _.get(face, 'email'), verified: true }];
        else
          user.emails = [];
      } else if (_.get(user, 'services.google')) {
        const google = _.get(user, 'services.google');
        user.profile = {
          firstName: _.get(google, 'given_name'),
          lastName: _.get(google, 'family_name'),
          name: _.get(google, 'name'),
          profilePic: _.get(google, 'picture'),
          gender: _.get(google, 'gender'),
        };
        if (_.get(google, 'email'))
          user.emails = [{ address: _.get(google, 'email'), verified: true }];
        else
          user.emails = [];
      } else if (options.profile) user.profile = options.profile;
```
O objeto de admin que pega do settings.json está em um formato diferente.
```
"admin" : {
   "email" : "root@root.com",
   "password" : "...."
},
```

Ai quando chama 
```
const { admin } = Meteor.settings.credentials;
...
const userId = Accounts.createUser(admin);
```
o hook seta user.email e não user.emails.

Uma possível solução seria editar o settings.json para o formato: 
```
emails: [{ address: "...", verified: true }]
```
ou então setar o user.emails no `else if (options.profile)`

**Comment by deleuterio** [comment]
https://github.com/lern-edu/lern/tree/bugfix/create-init-user-%23109
